services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80/tcp"
      - "8443:443/tcp"
    environment:
      TZ: "America/New_York"
      FTLCONF_webserver_api_password: "$PI_HOLE_ADMIN_PASSWORD"
      FTLCONF_dns_listeningMode: "ALL"
      FTLCONF_dns_upstreams: "unbound#53"
      FTLCONF_dns_specialDomains_iCloudPrivateRelay: "true"
    volumes:
      - "etc-pihole:/etc/pihole"
    cap_add:
      - NET_ADMIN
      - SYS_TIME
      - SYS_NICE
    networks:
      - dns_net
    deploy:
      placement:
        constraints:
          - node.hostname == $MANAGER_NODE
    restart: unless-stopped

volumes:
  etc-pihole:
    driver: local
    driver_opts:
      type: nfs
      o: addr=$NFS_IP,nolock,soft,rw
      device: ":$NFS_SHARED_DIR"

networks:
  dns_net:
    external: true
